### ISSUE TITLE
Where are the unanchored contigs?

### ISSUE THREAD

**Issue by Hollandlu** [tangerzhang/ALLHiC#132]
Hello @tanghaibao 
Tremendous work and more useful than 3d-DNA. I assembled a chromosome-level genome with 20 sequences.
But there is a little problem: where are the unanchored contigs?

The file named _groups.asm.fasta_ contains only 20 large sequences.

I also find a file named _unanchor.signal.txt_, could I use it to extract the unanchored contigs form somewhere?
Or any other methods that I can get the unanchored contig sequences?

It's likely impossible for the genome assembly to chromosome-level totally without contigs. 

Best wished and thanks a lot!

**Comment by tangerzhang** [comment]
Hi @Hollandlu 
Thanks for using ALLHiC. Along with `groups.asm.fasta`, there is a file `groups.agp`, which listed the positions of each contig. You can also find unanchored contigs in this file.  Otherwise, it is possible that all the contigs were anchored onto the chromosomes. If so, you can use the script `statAGP.pl` implanted in the ALLHiC package to calculate the anchoring rate.

**Comment by Hollandlu** [comment]
Hi @tangerzhang 
Wonderfully! The anchor rate is 100%, thanks a lot!
