### ISSUE TITLE
How to determine K value for diploid？

### ISSUE THREAD

**Issue by xiaoyuanbrother** [tangerzhang/ALLHiC#25]
Thank you for the algorithm！
But when I scaffoldof a simple diploid genome(1n = 2x = 16) with K value =8 , one of  clusters were  much bigger than the others. 
How to determine K value for diploid？

**Comment by tangerzhang** [comment]
K=8 should be the right number of the diploid genome you are working. The problem that one of the clusters is much bigger than others is mainly due to chimeric contigs based on my experiences. 
We have a discussion regarding the difficulty you are facing. Please check the following link for details: https://github.com/tangerzhang/ALLHiC/issues/8
