### ISSUE TITLE
How to determine K value for autopolyploid genome？

### ISSUE THREAD

**Issue by fantasticair** [tangerzhang/ALLHiC#26]
Hello
I assembly a autopolyploid genome.After colchicine treatment, the 28 chromosomes doubled to 56,for K=28 is right?

**Comment by tangerzhang** [comment]
Yes, K 28 is expected. The very recent genome duplication (e.g. colchicine treatment) resulted two sets of genome components, which should be exactly the same. When you assemble the contigs, the exactly same DNA sequences will be assembled together. That means you can only get 28 chromosomes rather than 56.
You may need to increase the K value, such as 56, 84, 112 or more, to get the phased haplotypes.
