### ISSUE TITLE
the group parameter

### ISSUE THREAD

**Issue by yangxiaofeill** [tangerzhang/ALLHiC#29]
Dear Dr. Zhang,
 I have tried `ALLHIC` to scaffolds our genome by HiC  data.  We skipped  `ALLHIC_prune` and `ALLHIC rescue` steps since our genome is a diploid genome. 
For the `ALLHiC_partition` step, there is a parameter -k, means group. I am wondering if the group number should be set as same as the chromosome number, e.g. our genome has 20 chromosomes, we should set k as 20? Or do you have any suggestions to set `k `value?

In my current project, I fond the final `group.asm.fasta` has 20 main scaffolds and a lot of contigs.  Alao, can I consider the `group.asm.fasta` as the final assembled genome? 

Best
Xiaofei

**Comment by tangerzhang** [comment]
Hi Xiaofei,
Based on your information, I assume the karyotype of this diploid genome is 2n=2x=20. If you have assembled a haplotype representation of the genome (i.e. 1 x has beed generated), the expected number of groups (k) in ALLHiC is 10 rather than 20. 
For the second question, `groups.asm.fasta` is the final assembled genome.

**Comment by yangxiaofeill** [comment]
Thanks for your quickly response.

**Comment by Rachel-pku** [comment]
Dear Dr. Zhang,
I am wondering how to set the K value. What is the haplotype representation of the genome ? My project's genome is  a diploid genome and the contig.fasta assembled by wtdbg and nextdenovo.  2n=2x=58

**Comment by tangerzhang** [comment]
> Dear Dr. Zhang,
> I am wondering how to set the K value. What is the haplotype representation of the genome ? My project's genome is a diploid genome and the contig.fasta assembled by wtdbg and nextdenovo. 2n=2x=58
In your case, K should be 29. The haplotype representation is the collapsed genome assembly with only one haplotype reported in the final release.

**Comment by DustinChen1986** [comment]
One issue is if I did not know the chromosome number of one species or the chromosome number is not correct. Can ALLHIC handle this issue?

**Comment by tangerzhang** [comment]
> One issue is if I did not know the chromosome number of one species or the chromosome number is not correct. Can ALLHIC handle this issue?

No. To our knowledge, no HiC assembler can accurately determine the chromosome number. If you do not know the exact number, you can randomly set a series of K values and determine the best one based on hic heatmap. But even if you can get a good result, it is not chromosomal level assembly. I suggest to use scaffold level assembly in your manuscript instead of chromosomal level.

**Comment by DustinChen1986** [comment]
Thank you for your explanation.
