### ISSUE TITLE
identify allelic contigs: Allele.ctg.table

### ISSUE THREAD

**Issue by YTLogos** [tangerzhang/ALLHiC#30]
Hi @tangerzhang 
Thanks for the great tool. I am wonder how to choose the well-assembled close related species.
For example, I study the *Brassica napus* (AACC, 2n = 4x = 38)), which is an allopolyploid and formed by interspecific hybridization between *B. rapa* (AA, 2n = 2x = 20) and *B. oleracea* (CC, 2n =2x = 18). Of course, It is really close related to *Arabidopsis*. So can I just choose *Aradopsis* or *B.rapa* or *B.oleracea* as the close related specie? As I know *Arabidopsis* is the best-assedmbled, and then *B.rapa*. Thanks!

**Comment by tangerzhang** [comment]
Since Brassica napus is an allo-tetraploid species and the two subgenomes contain substantial variations, you can treat the genome as a diploid genome and try ALLHiC with diploid genome scaffolding model first (i.e. no closely related reference used, and skip prune and rescue steps). 
Alternatively, if you want use prune to clean Hi-C signals between subgenomes, I would suggest B.rapa genome as it is much closer than Arabidopsis and has a better assembly as you have described.

**Comment by YTLogos** [comment]
> Since Brassica napus is an allo-tetraploid species and the two subgenomes contain substantial variations, you can treat the genome as a diploid genome and try ALLHiC with diploid genome scaffolding model first (i.e. no closely related reference used, and skip prune and rescue steps).
> Alternatively, if you want use prune to clean Hi-C signals between subgenomes, I would suggest B.rapa genome as it is much closer than Arabidopsis and has a better assembly as you have described.

Thank you for your prompt reply！That's really helpful.
