### ISSUE TITLE
Problem about mitochondrial genome

### ISSUE THREAD

**Issue by DustinChen1986** [tangerzhang/ALLHiC#49]
Report a problem about mitochondrial genome inserted in to chromosome by ALLHIC. So the mitochondrial genome should be excluded from the fasta file for HIC assemble.

**Comment by tangerzhang** [comment]
Thanks for reporting this issue. It happens when the genome contains inserted mitochondrial sequences during evolution. Hi-C signals will be detected between the previously inserted mitochondrial sequences and isolated mitochondrial genome.
I totally agree with you that it will be better to remove plasmid sequences before Hi-C scaffolding.

**Comment by tangerzhang** [comment]
Thanks for reporting this issue. It happens when the genome contains inserted mitochondrial sequences during evolution. Hi-C signals will be detected between the previously inserted mitochondrial sequences and isolated mitochondrial genome.
I totally agree with you that it will be better to remove plasmid sequences before Hi-C scaffolding.
