### ISSUE TITLE
partition and build probelem

### ISSUE THREAD

**Issue by a2431559261** [tangerzhang/ALLHiC#51]
hi,dear Tanger Zhang. i am confused for the step of  set -k for partition..Should K be the number of chromosomes or the number of chromesome sets (e.g., diploid, should K be 2?)And if -k is the total number of chromosomes (for example, a highly heterozygous diploid,  haploids have 20 chromosome,  diploids have 40 chromosome).I'm going to set -k to 40. How can I get the haploid chromosome from the total 40 chromosome?

thans for you share

**Comment by tangerzhang** [comment]
Hi @a2431559261 
K should be the number of chromosomes rather than set of haplotypes.
For a highly heterozgyous diploid genome (e.g. 2n=40), I will recommend you 1) remove the redundant sequences and then 2) hic scaffolding of one set of haplotypes with K=20. 
It is still quite difficult to assemble and phase two sets of haplotypes as it may need extensive manual correction.

**Comment by a2431559261** [comment]
ok,i will try the method that you recommed,thans a lot!
