### ISSUE TITLE
Could AllHic output  interaction sites information?

### ISSUE THREAD

**Issue by tianhao1225** [tangerzhang/ALLHiC#72]
hi, dr.zhang
could Allhic provides exactly interaction sites, to know like which region in chromosome closes to other region physically. can Allhic output a relative file?

Many thanks!

**Comment by tangerzhang** [comment]
Hi @tianhao1225 
ALLHiC is able to detect the interaction between contigs based on counting the number of paired-end reads that span contigs, rather than detection of restriction sites.  I am sorry that the answer is negative. Perhaps you can try some other tools that are designed for 3D genome studies.

**Comment by tianhao1225** [comment]
Hi Dr Zhang,

my question was not clear. We do not need ALLHiC to report interaction sites.

While what I wanted to know is whether ALLHiC can output the whole contact matrix which is used for drawing the contact map, i.e. converting the heat values at each bin of the pdf output to a text file (for which I think we just need to add some codes somewhere in your src file)?

Thanks.
Tianhao
