### ISSUE TITLE
how to get clusters.txt

### ISSUE THREAD

**Issue by cherrie-g** [tangerzhang/ALLHiC#73]
hi dr.zhang
I'm wondering that how to get the clusters.txt before ALLHIC_rescue. You said that it should be generated by allhic extract. But i run the allhic extract but it didn't generate the cluster.txt. 
I run just like this:
allhic extract sample.clean.bam genome.fa --RE AAGCTT
and it generated four files: sample.clean.counts_AAGCTT.txt, sample.clean.distribution.txt, sample.clean.clm and sample.clean.pairs.txt.
So did I run wrongly or should I deal with this four files to generate clusters.txt?
Also, i noticed that the prune step generate a prunning.clusters.txt, can this file used as clusters.txt?

**Comment by tangerzhang** [comment]
Hi @cherrie-g ,
My bad! The ```clusters.txt``` file was generated by ALLHiC_partition rather than allhic extract.
If you are working on a polyploid genome, then yes, ```prunning.clusters.txt``` could be used as clusters.txt.
Alternative, you can generate a ```clusters.txt``` file using your customized script according to the format of the cluster file.  
#Group  nContigs    Contigs
    48g1    506         tig0000150 tig0000151 tig0000152 
    48g2    692         tig0000097 tig0000114 tig0000231 
    48g3    683         tig0000015 tig0000035 tig0000235  
The first column is group name. The second is number of  contigs anchored in the group and the following columns list all of the contig names in the group.

**Comment by cherrie-g** [comment]
Thanks a lot.
And then I got another question. The count_RE.txt that rescue step needs should be the sample.clean.counts_RE.txt that generated by allhic extract? Or cat all prunning.counts_RE.*.txt that produced by partition step into one file and used this file as count_RE.txt?

**Comment by tangerzhang** [comment]
Yes, ```count_RE.txt``` is the same file with ```sample.clean.counts_RE.txt```, which could be generated by allhic extract
