### ISSUE TITLE
The files size of log.txt, removedb_Allele.txt, removedb_nonBest.txt are so big

### ISSUE THREAD

**Issue by Ahahaha3** [tangerzhang/ALLHiC#77]
hi, my genome size about 6.5G and i have conducted Allele.ctg.table, but when i run :ALLHiC_prune -i Allele.ctg.table -b sample.clean.bam -r draft.asm.fasta, my log.txt, removedb_Allele.txt and removedb_nonBest.txt 10T!! i dont know if it‘s right.

5101828915680 Jan 28 15:10 log.txt
1063596230477 Jan 28 15:10 removedb_Allele.txt
4475904064005 Jan 28 15:10 removedb_nonBest.txt

**Comment by Ahahaha3** [comment]
It's been running four days  T^T

**Comment by tangerzhang** [comment]
Hi @Ahahaha3 
Yes, this is right. We remained the log file for debug. If the genome you are working is big or Hi-C sequencing depth is high, the log file will be quite big. You can remove the log files once you finish prunning step. Alternatively, I will suggest you can first cluster contigs into homologous chromosome group before prunning as we did in the sugarcane genome (https://github.com/tangerzhang/ALLHiC/wiki/ALLHiC:-scaffolding-an-auto-polyploid-sugarcane-genome).
And one more reminding, are you working on a polyploid genome because there is no need to run ALLHiC_prune if this is a diploid genome.

**Comment by Ahahaha3** [comment]
Thanks for your replay. my genome is a diploid, but when i skip ALLHiC_prune, run ALLHiC_partition and my -k = 9, my result like  this:
  8773 group1.txt
   164 group2.txt
    76 group3.txt
    47 group4.txt
    49 group5.txt
    56 group6.txt
    10 group7.txt
    22 group8.txt
    14 group9.txt
group1 contains the most contigs. I have tried to increase the k=18, but group1 still has the most contigs.

**Comment by tangerzhang** [comment]
Hi @Ahahaha3 
The major problem is that the assembly contains many chimeric contigs. We have discussed this issue before and this thread possibly will provide useful information (https://github.com/tangerzhang/ALLHiC/issues/75).
